name: Build and Publish

on:
  push:
    tags:
      - 'v*'

env:
  APP_NAME: isdayoff                                        # set this to your application's name
  APP_PACKAGE_PATH: './published'                           # set this to the path to your app project, defaults to the repository root
  NETCORE_VERSION: '3.1.200'                                # set this to the .NET Core version to use
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}   # set this to access token to github.com
  GITHUB_TOKEN: ${{ github.token }}                         # set this to access token to github.com
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}               # set this to access token to nuget.org

jobs:
  build_and_publish:
    name: Build and Deploy    
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Pack
      run: dotnet pack ${{ env.APP_NAME }}/${{ env.APP_NAME }}.csproj --output nuget-packages --configuration Release
    
    - name: Add NuGet sources
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/${{ env.GITHUB_REPOSITORY_OWNER }}/index.json --name github --username ${{ env.GITHUB_REPOSITORY_OWNER }} --password ${{ env.GITHUB_TOKEN }} --store-password-in-clear-text
    
    - name: NuGet push on GitHub
      run: dotnet nuget push "**/*.nupkg" --source github --skip-duplicate
      
    - name: NuGet push on NuGet
      run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
    
    - name: Upload NuGet package
      uses: actions/upload-artifact@v2.1.4
      with:
        name: ${{ env.APP_NAME }}
        path: "**/*.nupkg"
